# Generated by Django 6.0.2 on 2026-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
